name: demo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.4
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#F7F6F1"
  color_dark: "#272727"
  image: assets/images/NOMI.png
  image_dark: assets/images/NOMI.png
  android: true
  ios: true
  fill: true



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
