name: demo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.4
  get: ^4.6.5
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.4.0+2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  dio: ^5.7.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  http: ^1.2.2
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^5.6.1
  provider: ^6.1.2
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#F7F6F1"
  color_dark: "#272727"
  image: assets/images/NOMI.png
  image_dark: assets/images/NOMI.png
  android: true
  ios: true
  fill: true



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
